// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfwN3PVZboHKEyzuOcNac_vfgPtDg3E7A',
    appId: '1:240103872232:web:268642922e84c89cf7db5d',
    messagingSenderId: '240103872232',
    projectId: 'projectsoutenance-8ad8c',
    authDomain: 'projectsoutenance-8ad8c.firebaseapp.com',
    storageBucket: 'projectsoutenance-8ad8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfFw3wxkFljH71oBFK3gF4qTVRYtx0Uy4',
    appId: '1:240103872232:android:8ebfd6ecfa431872f7db5d',
    messagingSenderId: '240103872232',
    projectId: 'projectsoutenance-8ad8c',
    storageBucket: 'projectsoutenance-8ad8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBalqs6BGrNdlg1zCDI9OrIiF21L1wEhNo',
    appId: '1:240103872232:ios:af363fc266d011daf7db5d',
    messagingSenderId: '240103872232',
    projectId: 'projectsoutenance-8ad8c',
    storageBucket: 'projectsoutenance-8ad8c.appspot.com',
    iosBundleId: 'com.example.emergency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBalqs6BGrNdlg1zCDI9OrIiF21L1wEhNo',
    appId: '1:240103872232:ios:af363fc266d011daf7db5d',
    messagingSenderId: '240103872232',
    projectId: 'projectsoutenance-8ad8c',
    storageBucket: 'projectsoutenance-8ad8c.appspot.com',
    iosBundleId: 'com.example.emergency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfwN3PVZboHKEyzuOcNac_vfgPtDg3E7A',
    appId: '1:240103872232:web:f2299947cce75addf7db5d',
    messagingSenderId: '240103872232',
    projectId: 'projectsoutenance-8ad8c',
    authDomain: 'projectsoutenance-8ad8c.firebaseapp.com',
    storageBucket: 'projectsoutenance-8ad8c.appspot.com',
  );
}
